### ISSUE TITLE
Error: Cannot find module 'winston'

### ISSUE THREAD

**Issue by karneaud** [evantahler/actionhero-tutorial#17]
deployed action hero on heroku....

in going through your tutorial [https://github.com/evantahler/actionhero-tutorial#getting-started-with-a-new-actionhero-project](url) I get the subject error.

I'm assuming that this was because of something specific to heroku?

**Comment by evantahler** [comment]
If you ran `npm install`, `winston` is installed as a dependency of actionhero.  Can you provide reproducible steps to get this error?

**Comment by karneaud** [comment]
Yep you were right...my bad on this as I thought I had already done that
